const std = @import("std");
const generated_header = @import("../generators/generated_header.zig");

test "render emits expected header" {
    const allocator = std.testing.allocator;
    const header = try generated_header.render(allocator, "0.6.0 (a1b2c3d)", "2026-07-12 21:49:56 UTC");
    defer allocator.free(header);

    try std.testing.expectEqualStrings(
        \\// this code was generated by openapi2zig 0.6.0 (a1b2c3d) on 2026-07-12 21:49:56 UTC
        \\// changes to this file may cause incorrect behavior and will be lost if the code is regenerated
        \\
        \\
    , header);
}
