const std = @import("std");
const generated_header = @import("../generators/generated_header.zig");
const openapi2zig = @import("../lib.zig");
const test_utils = @import("test_utils.zig");

test "render emits expected header" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const header = try generated_header.render(allocator, "0.6.0 (a1b2c3d)", "2026-07-12 21:49:56 UTC");
    defer allocator.free(header);

    try std.testing.expectEqualStrings(
        \\// <auto-generated>
        \\// this code was generated by openapi2zig 0.6.0 (a1b2c3d) on 2026-07-12 21:49:56 UTC
        \\// changes to this file may cause incorrect behavior and will be lost if the code is regenerated
        \\// </auto-generated>
        \\
        \\
    , header);
}

test "generateCode output includes generated header" {
    var gpa = test_utils.createTestAllocator();
    const allocator = gpa.allocator();
    defer std.debug.assert(gpa.deinit() == .ok);

    const json =
        \\{
        \\  "openapi": "3.0.0",
        \\  "info": { "title": "fixture", "version": "1.0.0" },
        \\  "paths": {}
        \\}
    ;

    var unified = try openapi2zig.parseToUnified(allocator, json);
    defer unified.deinit(allocator);

    const code = try openapi2zig.generateCode(allocator, std.testing.io, unified, .{
        .input_path = "fixture.json",
        .models_only = true,
    });
    defer allocator.free(code);

    try std.testing.expect(std.mem.indexOf(u8, code, "this code was generated by openapi2zig") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "changes to this file may cause incorrect behavior") != null);
    try std.testing.expect(std.mem.indexOf(u8, code, "will be lost if the code is regenerated") != null);
}
