const std = @import("std");
const version_info = @import("build_info");

pub fn render(allocator: std.mem.Allocator, version: []const u8, timestamp: []const u8) ![]const u8 {
    return try std.fmt.allocPrint(allocator,
        \\// <auto-generated>
        \\//   This code was generated by openapi2zig {s} on {s}
        \\//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
        \\// </auto-generated>
        \\
        \\
    , .{ version, timestamp });
}

pub fn renderWithChecksum(allocator: std.mem.Allocator, version: []const u8, timestamp: []const u8, checksum: u64) ![]const u8 {
    return try std.fmt.allocPrint(allocator,
        \\// <auto-generated>
        \\//   This code was generated by openapi2zig {s} on {s}
        \\//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
        \\//   Checksum: {x}
        \\// </auto-generated>
        \\
        \\
    , .{ version, timestamp, checksum });
}

pub fn renderNow(allocator: std.mem.Allocator, io: std.Io, version: []const u8) ![]const u8 {
    const timestamp = try formatUtcTimestamp(allocator, io);
    defer allocator.free(timestamp);
    return try render(allocator, version, timestamp);
}

pub fn renderNowFromBuildInfo(allocator: std.mem.Allocator, io: std.Io) ![]const u8 {
    const version = try std.fmt.allocPrint(allocator, "{s} ({s})", .{ version_info.VERSION, version_info.GIT_COMMIT });
    defer allocator.free(version);
    return try renderNow(allocator, io, version);
}

pub fn renderNowWithChecksum(allocator: std.mem.Allocator, io: std.Io, checksum: u64) ![]const u8 {
    const version = try std.fmt.allocPrint(allocator, "{s} ({s})", .{ version_info.VERSION, version_info.GIT_COMMIT });
    defer allocator.free(version);
    const timestamp = try formatUtcTimestamp(allocator, io);
    defer allocator.free(timestamp);
    return try renderWithChecksum(allocator, version, timestamp, checksum);
}

pub fn computeChecksum(code: []const u8) u64 {
    return std.hash.Wyhash.hash(0, code);
}

pub fn extractChecksum(content: []const u8) ?u64 {
    const marker = "//   Checksum: ";
    const start = std.mem.indexOf(u8, content, marker) orelse return null;
    const after = content[start + marker.len ..];
    const end = std.mem.indexOf(u8, after, "\n") orelse after.len;
    const hex_str = std.mem.trim(u8, after[0..end], " ");
    return std.fmt.parseInt(u64, hex_str, 16) catch null;
}

pub fn hasChanged(existing_content: []const u8, new_code: []const u8) bool {
    const existing_checksum = extractChecksum(existing_content) orelse return true;
    const new_checksum = computeChecksum(new_code);
    return existing_checksum != new_checksum;
}

fn formatUtcTimestamp(allocator: std.mem.Allocator, io: std.Io) ![]const u8 {
    const now = std.Io.Clock.real.now(io);
    const epoch_seconds = std.time.epoch.EpochSeconds{ .secs = @as(u64, @intCast(now.toSeconds())) };
    const epoch_day = epoch_seconds.getEpochDay();
    const day_seconds = epoch_seconds.getDaySeconds();
    const year_day = epoch_day.calculateYearDay();
    const month_day = year_day.calculateMonthDay();

    return try std.fmt.allocPrint(allocator, "{d}-{d:0>2}-{d:0>2} {d:0>2}:{d:0>2}:{d:0>2} UTC", .{
        year_day.year,
        month_day.month.numeric(),
        month_day.day_index + 1,
        day_seconds.getHoursIntoDay(),
        day_seconds.getMinutesIntoHour(),
        day_seconds.getSecondsIntoMinute(),
    });
}
