const std = @import("std");
const version_info = @import("build_info");

pub fn render(allocator: std.mem.Allocator, version: []const u8, timestamp: []const u8) ![]const u8 {
    return try std.fmt.allocPrint(allocator,
        \\// <auto-generated>
        \\// this code was generated by openapi2zig {s} on {s}
        \\// changes to this file may cause incorrect behavior and will be lost if the code is regenerated
        \\// </auto-generated>
        \\
    , .{ version, timestamp });
}

pub fn renderNow(allocator: std.mem.Allocator, io: std.Io, version: []const u8) ![]const u8 {
    const timestamp = try formatUtcTimestamp(allocator, io);
    defer allocator.free(timestamp);
    return try render(allocator, version, timestamp);
}

pub fn renderNowFromBuildInfo(allocator: std.mem.Allocator, io: std.Io) ![]const u8 {
    const version = try std.fmt.allocPrint(allocator, "{s} ({s})", .{ version_info.VERSION, version_info.GIT_COMMIT });
    defer allocator.free(version);
    return try renderNow(allocator, io, version);
}

fn formatUtcTimestamp(allocator: std.mem.Allocator, io: std.Io) ![]const u8 {
    const now = std.Io.Clock.real.now(io);
    const epoch_seconds = std.time.epoch.EpochSeconds{ .secs = @as(u64, @intCast(now.toSeconds())) };
    const epoch_day = epoch_seconds.getEpochDay();
    const day_seconds = epoch_seconds.getDaySeconds();
    const year_day = epoch_day.calculateYearDay();
    const month_day = year_day.calculateMonthDay();

    return try std.fmt.allocPrint(allocator, "{d}-{d:0>2}-{d:0>2} {d:0>2}:{d:0>2}:{d:0>2} UTC", .{
        year_day.year,
        month_day.month.numeric(),
        month_day.day_index + 1,
        day_seconds.getHoursIntoDay(),
        day_seconds.getMinutesIntoHour(),
        day_seconds.getSecondsIntoMinute(),
    });
}
