// <auto-generated>
//   This code was generated by openapi2zig 0.5.5 (9ac2677) on 2026-09-04 11:13:58 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: c07c62ecb7f3d651
// </auto-generated>

const std = @import("std");

pub const IssuePullRequest = struct {
    patch_url: ?[]const u8,
    diff_url: ?[]const u8,
    url: ?[]const u8,
    html_url: ?[]const u8,
    merged_at: ?[]const u8 = null,
};

pub const issue = struct {
    comments: i64,
    url: []const u8,
    pull_request: ?IssuePullRequest = null,
    pinned_comment: ?@"nullable-issue-comment" = null,
    body_html: ?[]const u8 = null,
    active_lock_reason: ?[]const u8 = null,
    issue_dependencies_summary: ?@"issue-dependencies-summary" = null,
    assignee: @"nullable-simple-user",
    comments_url: []const u8,
    id: i64,
    number: i64,
    reactions: ?@"reaction-rollup" = null,
    node_id: []const u8,
    body: ?[]const u8 = null,
    type: ?@"issue-type" = null,
    draft: ?bool = null,
    created_at: []const u8,
    timeline_url: ?[]const u8 = null,
    state: []const u8,
    state_reason: ?[]const u8 = null,
    assignees: ?[]const @"simple-user" = null,
    repository_url: []const u8,
    events_url: []const u8,
    milestone: @"nullable-milestone",
    locked: bool,
    body_text: ?[]const u8 = null,
    user: @"nullable-simple-user",
    performed_via_github_app: ?@"nullable-integration" = null,
    updated_at: []const u8,
    repository: ?repository = null,
    issue_field_values: ?[]const @"issue-field-value" = null,
    labels_url: []const u8,
    html_url: []const u8,
    labels: []const std.json.Value,
    author_association: ?[]const u8 = null,
    parent_issue_url: ?[]const u8 = null,
    closed_at: ?[]const u8,
    closed_by: ?@"nullable-simple-user" = null,
    sub_issues_summary: ?@"sub-issues-summary" = null,
    title: []const u8,
};

pub const @"issue-event-milestone" = struct {
    title: []const u8,
};

pub const TeamPermissions = struct {
    push: bool,
    admin: bool,
    maintain: bool,
    triage: bool,
    pull: bool,
};

pub const team = struct {
    enterprise_id: ?i64 = null,
    url: []const u8,
    permissions: ?TeamPermissions = null,
    privacy: ?[]const u8 = null,
    id: i64,
    members_url: []const u8,
    notification_setting: ?[]const u8 = null,
    parent: @"nullable-team-simple",
    html_url: []const u8,
    node_id: []const u8,
    access_source: ?[]const u8 = null,
    repositories_url: []const u8,
    description: ?[]const u8,
    organization_id: ?i64 = null,
    permission: []const u8,
    name: []const u8,
    type: []const u8,
    slug: []const u8,
};

pub const ValidationErrorErrorsItem = struct {
    resource: ?[]const u8 = null,
    value: ?std.json.Value = null,
    field: ?[]const u8 = null,
    message: ?[]const u8 = null,
    index: ?i64 = null,
    code: []const u8,
};

pub const @"validation-error" = struct {
    errors: ?[]const ValidationErrorErrorsItem = null,
    message: []const u8,
    documentation_url: []const u8,
};

pub const CommitParentsItem = struct {
    sha: []const u8,
    url: []const u8,
    html_url: ?[]const u8 = null,
};

pub const CommitStats = struct {
    deletions: ?i64 = null,
    additions: ?i64 = null,
    total: ?i64 = null,
};

pub const CommitCommitTree = struct {
    sha: []const u8,
    url: []const u8,
};

pub const CommitCommit = struct {
    author: @"nullable-git-user",
    url: []const u8,
    tree: CommitCommitTree,
    verification: ?verification = null,
    comment_count: i64,
    committer: @"nullable-git-user",
    message: []const u8,
};

pub const commit = struct {
    author: ?std.json.Value,
    parents: []const CommitParentsItem,
    url: []const u8,
    stats: ?CommitStats = null,
    html_url: []const u8,
    node_id: []const u8,
    files: ?[]const @"diff-entry" = null,
    sha: []const u8,
    committer: ?std.json.Value,
    commit: CommitCommit,
    comments_url: []const u8,
};

pub const @"issue-dependencies-summary" = struct {
    total_blocked_by: i64,
    blocked_by: i64,
    total_blocking: i64,
    blocking: i64,
};

pub const PullRequestSimpleBase = struct {
    sha: []const u8,
    ref: []const u8,
    label: []const u8,
    repo: repository,
    user: @"nullable-simple-user",
};

pub const PullRequestSimpleLinks = struct {
    statuses: link,
    comments: link,
    review_comments: link,
    review_comment: link,
    html: link,
    self: link,
    issue: link,
    commits: link,
};

pub const PullRequestSimpleLabelsItem = struct {
    default: bool,
    url: []const u8,
    color: []const u8,
    node_id: []const u8,
    description: []const u8,
    id: i64,
    name: []const u8,
};

pub const PullRequestSimpleHead = struct {
    sha: []const u8,
    ref: []const u8,
    label: []const u8,
    repo: repository,
    user: @"nullable-simple-user",
};

pub const @"pull-request-simple" = struct {
    url: []const u8,
    requested_teams: ?[]const team = null,
    statuses_url: []const u8,
    assignee: @"nullable-simple-user",
    active_lock_reason: ?[]const u8 = null,
    comments_url: []const u8,
    id: i64,
    base: PullRequestSimpleBase,
    number: i64,
    _links: PullRequestSimpleLinks,
    review_comment_url: []const u8,
    node_id: []const u8,
    body: ?[]const u8,
    draft: ?bool = null,
    review_comments_url: []const u8,
    created_at: []const u8,
    issue_url: []const u8,
    auto_merge: @"auto-merge",
    state: []const u8,
    assignees: ?[]const @"simple-user" = null,
    milestone: @"nullable-milestone",
    diff_url: []const u8,
    locked: bool,
    user: @"nullable-simple-user",
    merge_commit_sha: ?[]const u8,
    updated_at: []const u8,
    patch_url: []const u8,
    requested_reviewers: ?[]const @"simple-user" = null,
    labels: []const PullRequestSimpleLabelsItem,
    html_url: []const u8,
    head: PullRequestSimpleHead,
    author_association: []const u8,
    stack: ?@"pull-request-stack" = null,
    commits_url: []const u8,
    closed_at: ?[]const u8,
    merged_at: ?[]const u8,
    title: []const u8,
};

pub const @"team-simple" = struct {
    enterprise_id: ?i64 = null,
    url: []const u8,
    privacy: ?[]const u8 = null,
    id: i64,
    members_url: []const u8,
    notification_setting: ?[]const u8 = null,
    ldap_dn: ?[]const u8 = null,
    html_url: []const u8,
    node_id: []const u8,
    repositories_url: []const u8,
    description: ?[]const u8,
    organization_id: ?i64 = null,
    permission: []const u8,
    name: []const u8,
    type: []const u8,
    slug: []const u8,
};

pub const link = struct {
    href: []const u8,
};

pub const @"diff-entry" = struct {
    contents_url: []const u8,
    deletions: i64,
    patch: ?[]const u8 = null,
    sha: ?[]const u8,
    status: []const u8,
    filename: []const u8,
    additions: i64,
    previous_filename: ?[]const u8 = null,
    changes: i64,
    blob_url: []const u8,
    raw_url: []const u8,
};

pub const NullableIssuePullRequest = struct {
    patch_url: ?[]const u8,
    diff_url: ?[]const u8,
    url: ?[]const u8,
    html_url: ?[]const u8,
    merged_at: ?[]const u8 = null,
};

pub const @"nullable-issue" = struct {
    comments: i64,
    url: []const u8,
    pull_request: ?NullableIssuePullRequest = null,
    pinned_comment: ?@"nullable-issue-comment" = null,
    body_html: ?[]const u8 = null,
    active_lock_reason: ?[]const u8 = null,
    issue_dependencies_summary: ?@"issue-dependencies-summary" = null,
    assignee: @"nullable-simple-user",
    comments_url: []const u8,
    id: i64,
    number: i64,
    reactions: ?@"reaction-rollup" = null,
    node_id: []const u8,
    body: ?[]const u8 = null,
    type: ?@"issue-type" = null,
    draft: ?bool = null,
    created_at: []const u8,
    timeline_url: ?[]const u8 = null,
    state: []const u8,
    state_reason: ?[]const u8 = null,
    assignees: ?[]const @"simple-user" = null,
    repository_url: []const u8,
    events_url: []const u8,
    milestone: @"nullable-milestone",
    locked: bool,
    body_text: ?[]const u8 = null,
    user: @"nullable-simple-user",
    performed_via_github_app: ?@"nullable-integration" = null,
    updated_at: []const u8,
    repository: ?repository = null,
    issue_field_values: ?[]const @"issue-field-value" = null,
    labels_url: []const u8,
    html_url: []const u8,
    labels: []const std.json.Value,
    author_association: ?[]const u8 = null,
    parent_issue_url: ?[]const u8 = null,
    closed_at: ?[]const u8,
    closed_by: ?@"nullable-simple-user" = null,
    sub_issues_summary: ?@"sub-issues-summary" = null,
    title: []const u8,
};

pub const @"reaction-rollup" = struct {
    @"-1": i64,
    heart: i64,
    url: []const u8,
    @"+1": i64,
    hooray: i64,
    eyes: i64,
    confused: i64,
    rocket: i64,
    laugh: i64,
    total_count: i64,
};

pub const @"nullable-team-simple" = struct {
    enterprise_id: ?i64 = null,
    url: []const u8,
    privacy: ?[]const u8 = null,
    id: i64,
    members_url: []const u8,
    notification_setting: ?[]const u8 = null,
    ldap_dn: ?[]const u8 = null,
    html_url: []const u8,
    node_id: []const u8,
    repositories_url: []const u8,
    description: ?[]const u8,
    organization_id: ?i64 = null,
    permission: []const u8,
    name: []const u8,
    type: []const u8,
    slug: []const u8,
};

pub const @"simple-repository" = struct {
    private: bool,
    forks_url: []const u8,
    url: []const u8,
    assignees_url: []const u8,
    blobs_url: []const u8,
    fork: bool,
    issue_comment_url: []const u8,
    statuses_url: []const u8,
    compare_url: []const u8,
    comments_url: []const u8,
    id: i64,
    stargazers_url: []const u8,
    languages_url: []const u8,
    subscribers_url: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    git_tags_url: []const u8,
    subscription_url: []const u8,
    downloads_url: []const u8,
    contents_url: []const u8,
    pulls_url: []const u8,
    tags_url: []const u8,
    trees_url: []const u8,
    archive_url: []const u8,
    contributors_url: []const u8,
    owner: @"simple-user",
    git_commits_url: []const u8,
    hooks_url: []const u8,
    events_url: []const u8,
    issues_url: []const u8,
    keys_url: []const u8,
    full_name: []const u8,
    notifications_url: []const u8,
    releases_url: []const u8,
    branches_url: []const u8,
    labels_url: []const u8,
    html_url: []const u8,
    issue_events_url: []const u8,
    milestones_url: []const u8,
    teams_url: []const u8,
    commits_url: []const u8,
    collaborators_url: []const u8,
    deployments_url: []const u8,
    name: []const u8,
    git_refs_url: []const u8,
    merges_url: []const u8,
};

pub const RepositoryPermissions = struct {
    push: bool,
    admin: bool,
    maintain: ?bool = null,
    triage: ?bool = null,
    pull: bool,
};

pub const RepositoryCodeSearchIndexStatus = struct {
    lexical_search_ok: ?bool = null,
    lexical_commit_sha: ?[]const u8 = null,
};

pub const repository = struct {
    deployments_url: []const u8,
    pull_request_creation_policy: ?[]const u8 = null,
    has_wiki: bool,
    assignees_url: []const u8,
    blobs_url: []const u8,
    name: []const u8,
    forks_count: i64,
    has_issues: bool,
    watchers_count: i64,
    visibility: ?[]const u8 = null,
    comments_url: []const u8,
    default_branch: []const u8,
    stargazers_url: []const u8,
    mirror_url: ?[]const u8,
    starred_at: ?[]const u8 = null,
    watchers: i64,
    has_pages: bool,
    node_id: []const u8,
    has_discussions: ?bool = null,
    has_downloads: bool,
    archived: bool,
    web_commit_signoff_required: ?bool = null,
    subscription_url: []const u8,
    clone_url: []const u8,
    language: ?[]const u8,
    merge_commit_message: ?[]const u8 = null,
    allow_merge_commit: ?bool = null,
    contents_url: []const u8,
    pulls_url: []const u8,
    archive_url: []const u8,
    full_name: []const u8,
    notifications_url: []const u8,
    open_issues: i64,
    ssh_url: []const u8,
    html_url: []const u8,
    milestones_url: []const u8,
    open_issues_count: i64,
    git_refs_url: []const u8,
    merges_url: []const u8,
    compare_url: []const u8,
    private: bool,
    forks_url: []const u8,
    url: []const u8,
    issue_comment_url: []const u8,
    topics: ?[]const []const u8 = null,
    fork: bool,
    statuses_url: []const u8,
    has_pull_requests: ?bool = null,
    temp_clone_token: ?[]const u8 = null,
    allow_squash_merge: ?bool = null,
    delete_branch_on_merge: ?bool = null,
    merge_commit_title: ?[]const u8 = null,
    id: i64,
    allow_forking: ?bool = null,
    forks: i64,
    languages_url: []const u8,
    subscribers_url: []const u8,
    homepage: ?[]const u8,
    has_projects: bool,
    pushed_at: ?[]const u8,
    squash_merge_commit_title: ?[]const u8 = null,
    description: ?[]const u8,
    git_tags_url: []const u8,
    svn_url: []const u8,
    git_url: []const u8,
    downloads_url: []const u8,
    trees_url: []const u8,
    tags_url: []const u8,
    created_at: ?[]const u8,
    use_squash_pr_title_as_default: ?bool = null,
    license: @"nullable-license-simple",
    anonymous_access_enabled: ?bool = null,
    permissions: ?RepositoryPermissions = null,
    master_branch: ?[]const u8 = null,
    owner: @"simple-user",
    squash_merge_commit_message: ?[]const u8 = null,
    contributors_url: []const u8,
    git_commits_url: []const u8,
    events_url: []const u8,
    issues_url: []const u8,
    hooks_url: []const u8,
    keys_url: []const u8,
    is_template: ?bool = null,
    allow_rebase_merge: ?bool = null,
    updated_at: ?[]const u8,
    releases_url: []const u8,
    branches_url: []const u8,
    size: i64,
    labels_url: []const u8,
    disabled: bool,
    issue_events_url: []const u8,
    allow_auto_merge: ?bool = null,
    stargazers_count: i64,
    allow_update_branch: ?bool = null,
    teams_url: []const u8,
    commits_url: []const u8,
    collaborators_url: []const u8,
    code_search_index_status: ?RepositoryCodeSearchIndexStatus = null,
};

pub const PullRequestReviewLinksPullRequest = struct {
    href: []const u8,
};

pub const PullRequestReviewLinksHtml = struct {
    href: []const u8,
};

pub const PullRequestReviewLinks = struct {
    pull_request: PullRequestReviewLinksPullRequest,
    html: PullRequestReviewLinksHtml,
};

pub const @"pull-request-review" = struct {
    pull_request_url: []const u8,
    state: []const u8,
    body_html: ?[]const u8 = null,
    commit_id: ?[]const u8,
    body_text: ?[]const u8 = null,
    id: i64,
    user: @"nullable-simple-user",
    _links: PullRequestReviewLinks,
    html_url: []const u8,
    node_id: []const u8,
    author_association: []const u8,
    submitted_at: ?[]const u8 = null,
    body: []const u8,
};

pub const @"pull-request-merge-async-result" = struct {
    status: []const u8,
    details: std.json.Value,
};

pub const @"issue-event-rename" = struct {
    from: []const u8,
    to: []const u8,
};

pub const @"issue-comment" = struct {
    created_at: []const u8,
    url: []const u8,
    issue_url: []const u8,
    body_html: ?[]const u8 = null,
    body_text: ?[]const u8 = null,
    performed_via_github_app: ?@"nullable-integration" = null,
    id: i64,
    user: @"nullable-simple-user",
    updated_at: []const u8,
    reactions: ?@"reaction-rollup" = null,
    html_url: []const u8,
    node_id: []const u8,
    author_association: ?[]const u8 = null,
    pin: ?@"nullable-pinned-issue-comment" = null,
    body: ?[]const u8 = null,
    minimized: ?@"nullable-issue-comment-minimized" = null,
};

pub const @"issue-suggestion" = struct {
    created_at: []const u8,
    target_value: ?std.json.Value,
    actor_id: ?i64,
    state: []const u8,
    confidence: ?[]const u8,
    action: []const u8,
    id: i64,
    issue_event_id: ?i64,
    resolved_by: ?i64,
    updated_at: []const u8,
    rationale: ?[]const u8,
    target_id: ?i64,
    issue_id: i64,
};

pub const @"issue-event-project-card" = struct {
    column_name: []const u8,
    project_id: i64,
    url: []const u8,
    id: i64,
    previous_column_name: ?[]const u8 = null,
    project_url: []const u8,
};

pub const label = struct {
    default: bool,
    url: []const u8,
    color: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    id: i64,
    name: []const u8,
};

pub const @"nullable-simple-user" = struct {
    url: []const u8,
    subscriptions_url: []const u8,
    organizations_url: []const u8,
    email: ?[]const u8 = null,
    login: []const u8,
    gists_url: []const u8,
    events_url: []const u8,
    gravatar_id: ?[]const u8,
    id: i64,
    repos_url: []const u8,
    followers_url: []const u8,
    starred_url: []const u8,
    starred_at: ?[]const u8 = null,
    html_url: []const u8,
    node_id: []const u8,
    site_admin: bool,
    user_view_type: ?[]const u8 = null,
    following_url: []const u8,
    avatar_url: []const u8,
    name: ?[]const u8 = null,
    received_events_url: []const u8,
    type: []const u8,
};

pub const @"nullable-milestone" = struct {
    created_at: []const u8,
    url: []const u8,
    state: []const u8,
    id: i64,
    creator: @"nullable-simple-user",
    due_on: ?[]const u8,
    updated_at: []const u8,
    number: i64,
    open_issues: i64,
    labels_url: []const u8,
    html_url: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    closed_at: ?[]const u8,
    title: []const u8,
    closed_issues: i64,
};

pub const @"issue-event-dismissed-review" = struct {
    state: []const u8,
    dismissal_message: ?[]const u8,
    review_id: i64,
    dismissal_commit_id: ?[]const u8 = null,
};

pub const @"pull-request-review-request" = struct {
    users: []const @"simple-user",
    teams: []const team,
};

pub const PullRequestReviewCommentLinksSelf = struct {
    href: []const u8,
};

pub const PullRequestReviewCommentLinksPullRequest = struct {
    href: []const u8,
};

pub const PullRequestReviewCommentLinksHtml = struct {
    href: []const u8,
};

pub const PullRequestReviewCommentLinks = struct {
    self: PullRequestReviewCommentLinksSelf,
    pull_request: PullRequestReviewCommentLinksPullRequest,
    html: PullRequestReviewCommentLinksHtml,
};

pub const @"pull-request-review-comment" = struct {
    pull_request_url: []const u8,
    original_position: ?i64 = null,
    url: []const u8,
    position: ?i64 = null,
    body_html: ?[]const u8 = null,
    in_reply_to_id: ?i64 = null,
    id: i64,
    original_start_line: ?i64 = null,
    _links: PullRequestReviewCommentLinks,
    reactions: ?@"reaction-rollup" = null,
    subject_type: ?[]const u8 = null,
    node_id: []const u8,
    diff_hunk: []const u8,
    start_line: ?i64 = null,
    side: ?[]const u8 = null,
    original_commit_id: []const u8,
    body: []const u8,
    created_at: []const u8,
    start_side: ?[]const u8 = null,
    commit_id: []const u8,
    line: ?i64 = null,
    body_text: ?[]const u8 = null,
    user: @"nullable-simple-user",
    pull_request_review_id: ?i64,
    updated_at: []const u8,
    html_url: []const u8,
    author_association: []const u8,
    path: []const u8,
    original_line: ?i64 = null,
};

pub const @"nullable-issue-comment-minimized" = struct {
    reason: ?[]const u8,
};

pub const @"author-association" = []const u8;

pub const PullRequestStackBase = struct {
    sha: []const u8,
    ref: []const u8,
};

pub const @"pull-request-stack" = struct {
    size: ?i64 = null,
    position: ?i64 = null,
    id: ?i64 = null,
    base: PullRequestStackBase,
    number: ?i64 = null,
};

pub const @"pull-request-merge-result" = struct {
    sha: []const u8,
    merged: bool,
    message: []const u8,
};

pub const NullableIntegrationPermissions = struct {
    issues: ?[]const u8 = null,
    checks: ?[]const u8 = null,
    metadata: ?[]const u8 = null,
    deployments: ?[]const u8 = null,
    contents: ?[]const u8 = null,
};

pub const @"nullable-integration" = struct {
    created_at: []const u8,
    client_id: ?[]const u8 = null,
    owner: std.json.Value,
    permissions: NullableIntegrationPermissions,
    events: []const []const u8,
    id: i64,
    updated_at: []const u8,
    html_url: []const u8,
    node_id: []const u8,
    installations_count: ?i64 = null,
    description: ?[]const u8,
    name: []const u8,
    external_url: []const u8,
    slug: ?[]const u8 = null,
};

pub const milestone = struct {
    created_at: []const u8,
    url: []const u8,
    state: []const u8,
    id: i64,
    creator: @"nullable-simple-user",
    due_on: ?[]const u8,
    updated_at: []const u8,
    number: i64,
    open_issues: i64,
    labels_url: []const u8,
    html_url: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    closed_at: ?[]const u8,
    title: []const u8,
    closed_issues: i64,
};

pub const @"issue-event" = struct {
    url: []const u8,
    assignee: ?@"nullable-simple-user" = null,
    rename: ?@"issue-event-rename" = null,
    id: i64,
    requested_reviewer: ?@"nullable-simple-user" = null,
    requested_team: ?team = null,
    blocked_by: ?@"nullable-issue-reference" = null,
    node_id: []const u8,
    parent_issue: ?@"nullable-issue-reference" = null,
    assigner: ?@"nullable-simple-user" = null,
    lock_reason: ?[]const u8 = null,
    commit_url: ?[]const u8,
    event: []const u8,
    issue: ?@"nullable-issue" = null,
    review_requester: ?@"nullable-simple-user" = null,
    blocking: ?@"nullable-issue-reference" = null,
    created_at: []const u8,
    dismissed_review: ?@"issue-event-dismissed-review" = null,
    sub_issue: ?@"nullable-issue-reference" = null,
    commit_id: ?[]const u8,
    milestone: ?@"issue-event-milestone" = null,
    actor: @"nullable-simple-user",
    performed_via_github_app: ?@"nullable-integration" = null,
    issue_type: ?@"issue-type-webhook" = null,
    project_card: ?@"issue-event-project-card" = null,
    intent: ?@"nullable-issue-event-intent" = null,
    author_association: ?[]const u8 = null,
    prev_issue_type: ?@"issue-type-webhook" = null,
    label: ?@"issue-event-label" = null,
};

pub const ReviewCommentLinks = struct {
    self: link,
    pull_request: link,
    html: link,
};

pub const @"review-comment" = struct {
    pull_request_url: []const u8,
    original_position: i64,
    url: []const u8,
    position: ?i64,
    body_html: ?[]const u8 = null,
    in_reply_to_id: ?i64 = null,
    id: i64,
    original_start_line: ?i64 = null,
    _links: ReviewCommentLinks,
    reactions: ?@"reaction-rollup" = null,
    subject_type: ?[]const u8 = null,
    node_id: []const u8,
    diff_hunk: []const u8,
    start_line: ?i64 = null,
    original_commit_id: []const u8,
    body: []const u8,
    side: ?[]const u8 = null,
    created_at: []const u8,
    start_side: ?[]const u8 = null,
    commit_id: []const u8,
    body_text: ?[]const u8 = null,
    line: ?i64 = null,
    user: @"nullable-simple-user",
    pull_request_review_id: ?i64,
    updated_at: []const u8,
    html_url: []const u8,
    author_association: []const u8,
    path: []const u8,
    original_line: ?i64 = null,
};

pub const @"nullable-git-user" = struct {
    date: ?[]const u8 = null,
    name: ?[]const u8 = null,
    email: ?[]const u8 = null,
};

pub const @"issue-type-webhook" = struct {
    color: ?[]const u8 = null,
    id: i64,
    name: []const u8,
};

pub const @"nullable-issue-event-intent" = struct {
    rationale: ?[]const u8 = null,
    confidence: ?[]const u8 = null,
};

pub const @"issue-type" = struct {
    created_at: ?[]const u8 = null,
    color: ?[]const u8 = null,
    node_id: []const u8,
    is_enabled: ?bool = null,
    description: ?[]const u8,
    id: i64,
    name: []const u8,
    updated_at: ?[]const u8 = null,
};

pub const verification = struct {
    payload: ?[]const u8,
    verified: bool,
    reason: []const u8,
    signature: ?[]const u8,
    verified_at: ?[]const u8,
};

pub const IssueFieldValueSingleSelectOption = struct {
    color: []const u8,
    id: i64,
    name: []const u8,
};

pub const IssueFieldValueMultiSelectOptionsItem = struct {
    color: []const u8,
    id: i64,
    name: []const u8,
};

pub const @"issue-field-value" = struct {
    issue_field_name: ?[]const u8 = null,
    single_select_option: ?IssueFieldValueSingleSelectOption = null,
    node_id: []const u8,
    issue_field_id: i64,
    value: ?std.json.Value,
    multi_select_options: ?[]const IssueFieldValueMultiSelectOptionsItem = null,
    data_type: []const u8,
};

pub const @"timeline-issue-events" = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const PullRequestBase = struct {
    sha: []const u8,
    ref: []const u8,
    label: []const u8,
    repo: repository,
    user: @"simple-user",
};

pub const PullRequestLinks = struct {
    statuses: link,
    comments: link,
    review_comments: link,
    review_comment: link,
    html: link,
    self: link,
    issue: link,
    commits: link,
};

pub const PullRequestLabelsItem = struct {
    default: bool,
    url: []const u8,
    color: []const u8,
    node_id: []const u8,
    description: ?[]const u8,
    id: i64,
    name: []const u8,
};

pub const PullRequestHead = struct {
    sha: []const u8,
    ref: []const u8,
    label: []const u8,
    repo: repository,
    user: @"simple-user",
};

pub const @"pull-request" = struct {
    comments: i64,
    url: []const u8,
    review_comments: i64,
    statuses_url: []const u8,
    active_lock_reason: ?[]const u8 = null,
    assignee: @"nullable-simple-user",
    requested_teams: ?[]const @"team-simple" = null,
    merged: bool,
    comments_url: []const u8,
    id: i64,
    base: PullRequestBase,
    number: i64,
    _links: PullRequestLinks,
    deletions: i64,
    review_comment_url: []const u8,
    node_id: []const u8,
    changed_files: i64,
    mergeable: ?bool,
    merged_by: @"nullable-simple-user",
    mergeable_state: []const u8,
    body: ?[]const u8,
    commits: i64,
    draft: ?bool = null,
    review_comments_url: []const u8,
    created_at: []const u8,
    issue_url: []const u8,
    auto_merge: @"auto-merge",
    state: []const u8,
    assignees: ?[]const @"simple-user" = null,
    milestone: @"nullable-milestone",
    diff_url: []const u8,
    locked: bool,
    maintainer_can_modify: bool,
    user: @"simple-user",
    merge_commit_sha: ?[]const u8,
    updated_at: []const u8,
    patch_url: []const u8,
    requested_reviewers: ?[]const @"simple-user" = null,
    rebaseable: ?bool = null,
    labels: []const PullRequestLabelsItem,
    html_url: []const u8,
    head: PullRequestHead,
    author_association: []const u8,
    stack: ?@"pull-request-stack" = null,
    additions: i64,
    commits_url: []const u8,
    closed_at: ?[]const u8,
    merged_at: ?[]const u8,
    title: []const u8,
};

pub const @"auto-merge" = struct {
    commit_message: []const u8,
    commit_title: []const u8,
    enabled_by: @"simple-user",
    merge_method: []const u8,
};

pub const @"sub-issues-summary" = struct {
    completed: i64,
    percent_completed: i64,
    total: i64,
};

pub const @"nullable-license-simple" = struct {
    node_id: []const u8,
    url: ?[]const u8,
    html_url: ?[]const u8 = null,
    key: []const u8,
    name: []const u8,
    spdx_id: ?[]const u8,
};

pub const @"issue-event-label" = struct {
    color: ?[]const u8,
    name: ?[]const u8,
};

pub const @"simple-user" = struct {
    url: []const u8,
    subscriptions_url: []const u8,
    organizations_url: []const u8,
    email: ?[]const u8 = null,
    login: []const u8,
    gists_url: []const u8,
    events_url: []const u8,
    gravatar_id: ?[]const u8,
    id: i64,
    repos_url: []const u8,
    followers_url: []const u8,
    starred_url: []const u8,
    starred_at: ?[]const u8 = null,
    html_url: []const u8,
    node_id: []const u8,
    site_admin: bool,
    user_view_type: ?[]const u8 = null,
    following_url: []const u8,
    avatar_url: []const u8,
    name: ?[]const u8 = null,
    received_events_url: []const u8,
    type: []const u8,
};

pub const NullableIssueReferenceIssueType = struct {
    color: ?[]const u8 = null,
    id: i64,
    node_id: []const u8,
    name: []const u8,
};

pub const @"nullable-issue-reference" = struct {
    repository: @"simple-repository",
    title: []const u8,
    number: i64,
    state: []const u8,
    state_reason: ?[]const u8 = null,
    issue_type: ?NullableIssueReferenceIssueType,
};

pub const PullRequestStackMinimalPullRequestsItemHead = struct {
    sha: []const u8,
    ref: []const u8,
};

pub const PullRequestStackMinimalPullRequestsItem = struct {
    number: i64,
    state: []const u8,
    head: PullRequestStackMinimalPullRequestsItemHead,
    merged_at: ?[]const u8,
    draft: bool,
};

pub const PullRequestStackMinimalBase = struct {
    ref: []const u8,
};

pub const @"pull-request-stack-minimal" = struct {
    created_at: []const u8,
    url: []const u8,
    open: bool,
    node_id: []const u8,
    pull_requests: []const PullRequestStackMinimalPullRequestsItem,
    id: i64,
    base: PullRequestStackMinimalBase,
    number: i64,
};

pub const @"pull-request-stack-pull-request" = union(enum) {
    null,
    bool: bool,
    integer: i64,
    float: f64,
    number_string: []const u8,
    string: []const u8,
    array: std.json.Array,
    object: std.json.ObjectMap,

    pub fn jsonParse(allocator: std.mem.Allocator, source: anytype, options: std.json.ParseOptions) !@This() {
        const value = try std.json.innerParse(std.json.Value, allocator, source, options);
        return jsonParseFromValue(allocator, value, options);
    }

    pub fn jsonParseFromValue(_: std.mem.Allocator, source: std.json.Value, _: std.json.ParseOptions) !@This() {
        return switch (source) {
            .null => .null,
            .bool => |value| .{ .bool = value },
            .integer => |value| .{ .integer = value },
            .float => |value| .{ .float = value },
            .number_string => |value| .{ .number_string = value },
            .string => |value| .{ .string = value },
            .array => |value| .{ .array = value },
            .object => |value| .{ .object = value },
        };
    }

    pub fn jsonStringify(self: @This(), jw: *std.json.Stringify) !void {
        switch (self) {
            .null => try jw.write(null),
            .bool => |value| try jw.write(value),
            .integer => |value| try jw.write(value),
            .float => |value| try jw.write(value),
            .number_string => |value| try jw.print("{s}", .{value}),
            .string => |value| try jw.write(value),
            .array => |value| try jw.write(value.items),
            .object => |value| {
                try jw.beginObject();
                var iterator = value.iterator();
                while (iterator.next()) |entry| {
                    try jw.objectField(entry.key_ptr.*);
                    try jw.write(entry.value_ptr.*);
                }
                try jw.endObject();
            },
        }
    }
};

pub const @"basic-error" = struct {
    status: ?[]const u8 = null,
    url: ?[]const u8 = null,
    message: ?[]const u8 = null,
    documentation_url: ?[]const u8 = null,
};

pub const @"nullable-issue-comment" = struct {
    created_at: []const u8,
    url: []const u8,
    issue_url: []const u8,
    body_html: ?[]const u8 = null,
    body_text: ?[]const u8 = null,
    performed_via_github_app: ?@"nullable-integration" = null,
    id: i64,
    user: @"nullable-simple-user",
    updated_at: []const u8,
    reactions: ?@"reaction-rollup" = null,
    html_url: []const u8,
    node_id: []const u8,
    author_association: ?[]const u8 = null,
    pin: ?@"nullable-pinned-issue-comment" = null,
    body: ?[]const u8 = null,
    minimized: ?@"nullable-issue-comment-minimized" = null,
};

pub const @"nullable-pinned-issue-comment" = struct {
    pinned_by: @"nullable-simple-user",
    pinned_at: []const u8,
};

pub const @"issue-event-for-issue" = std.json.Value;
